export const FETCH_GOODS_START = 'FETCH_GOODS_START'
export const FETCH_GOODS_SUCCESS = 'FETCH_GOODS_SUCCESS'
export const FETCH_GOODS_FAIL = 'FETCH_GOODS_FAIL'
export const FILTER_GOODS = 'FILTER_GOODS'

export const ADD_GOOD_TO_CART = 'ADD_GOOD_TO_CART'
export const REMOVE_ONE_GOOD_FROM_CART = 'REMOVE_ONE_GOOD_FROM_CART'
export const REMOVE_GOOD_FROM_CART = 'REMOVE_GOOD_FROM_CART'
export const CLEAR_CART = 'CLEAR_CART'